// eslint-disable-next-line
const countries = [  
    { value: 'All countries', label: 'Всі країни' },
    { value: 'Afghanistan', label: 'Афганістан' },
    { value: 'Albania', label: 'Албанія' },
    { value: 'Algeria', label: 'Алжир' },
    { value: 'Andorra', label: 'Андорра' },
    { value: 'Angola', label: 'Ангола' },
    { value: 'Antigua and Barbuda', label: 'Антигуа і Барбуда' },
    { value: 'Argentina', label: 'Аргентина' },
    { value: 'Armenia', label: 'Вірменія' },
    { value: 'Australia', label: 'Австралія' },
    { value: 'Austria', label: 'Австрія' },
    { value: 'Azerbaijan', label: 'Азербайджан' },
    { value: 'Bahamas', label: 'Багамські Острови' },
    { value: 'Bahrain', label: 'Бахрейн' },
    { value: 'Bangladesh', label: 'Бангладеш' },
    { value: 'Barbados', label: 'Барбадос' },
    { value: 'Belarus', label: 'Білорусь' },
    { value: 'Belgium', label: 'Бельгія' },
    { value: 'Belize', label: 'Беліз' },
    { value: 'Benin', label: 'Бенін' },
    { value: 'Bhutan', label: 'Бутан' },
    { value: 'Bolivia', label: 'Болівія' },
    { value: 'Bosnia and Herzegovina', label: 'Боснія і Герцеговина' },
    { value: 'Botswana', label: 'Ботсвана' },
    { value: 'Brazil', label: 'Бразилія' },
    { value: 'Brunei', label: 'Бруней' },
    { value: 'Bulgaria', label: 'Болгарія' },
    { value: 'Burkina Faso', label: 'Буркіна-Фасо' },
    { value: 'Burundi', label: 'Бурунді' },
    { value: 'Cabo Verde', label: 'Кабо-Верде' },
    { value: 'Cambodia', label: 'Камбоджа' },
    { value: 'Cameroon', label: 'Камерун' },
    { value: 'Canada', label: 'Канада' },
    { value: 'Central African Republic', label: 'Центральноафриканська Республіка' },
    { value: 'Chad', label: 'Чад' },
    { value: 'Chile', label: 'Чилі' },
    { value: 'China', label: 'Китай' },
    { value: 'Colombia', label: 'Колумбія' },
    { value: 'Comoros', label: 'Коморські острови' },
    { value: 'Congo', label: 'Конго' },
    { value: 'Costa Rica', label: 'Коста-Ріка' },
    { value: 'Croatia', label: 'Хорватія' },
    { value: 'Cuba', label: 'Куба' },
    { value: 'Cyprus', label: 'Кіпр' },
    { value: 'Czechia', label: 'Чехія' },
    { value: 'Denmark', label: 'Данія' },
    { value: 'Djibouti', label: 'Джибуті' },
    { value: 'Dominica', label: 'Домініка' },
    { value: 'Dominican Republic', label: 'Домініканська Республіка' },
    { value: 'Ecuador', label: 'Еквадор' },
    { value: 'Egypt', label: 'Єгипет' },
    { value: 'El Salvador', label: 'Сальвадор' },
    { value: 'Equatorial Guinea', label: 'Екваторіальна Гвінея' },
    { value: 'Eritrea', label: 'Еритрея' },
    { value: 'Estonia', label: 'Естонія' },
    { value: 'Eswatini', label: 'Есватіні' },
    { value: 'Ethiopia', label: 'Ефіопія' },
    { value: 'Fiji', label: 'Фіджі' },
    { value: 'Finland', label: 'Фінляндія' },
    { value: 'France', label: 'Франція' },
    { value: 'Gabon', label: 'Габон' },
    { value: 'Gambia', label: 'Гамбія' },
    { value: 'Georgia', label: 'Грузія' },
    { value: 'Germany', label: 'Німеччина' },
    { value: 'Ghana', label: 'Гана' },
    { value: 'Greece', label: 'Греція' },
    { value: 'Grenada', label: 'Гренада' },
    { value: 'Guatemala', label: 'Гватемала' },
    { value: 'Guinea', label: 'Гвінея' },
    { value: 'Guinea-Bissau', label: 'Гвінея-Бісау' },
    { value: 'Guyana', label: 'Гайана' },
    { value: 'Haiti', label: 'Гаїті' },
    { value: 'Honduras', label: 'Гондурас' },
    { value: 'Hungary', label: 'Угорщина' },
    { value: 'Iceland', label: 'Ісландія' },
    { value: 'India', label: 'Індія' },
    { value: 'Indonesia', label: 'Індонезія' },
    { value: 'Iran', label: 'Іран' },
    { value: 'Iraq', label: 'Ірак' },
    { value: 'Ireland', label: 'Ірландія' },
    { value: 'Israel', label: 'Ізраїль' },
    { value: 'Italy', label: 'Італія' },
    { value: 'Jamaica', label: 'Ямайка' },
    { value: 'Japan', label: 'Японія' },
    { value: 'Jordan', label: 'Йорданія' },
    { value: 'Kazakhstan', label: 'Казахстан' },
    { value: 'Kenya', label: 'Кенія' },
    { value: 'Kiribati', label: 'Кірибаті' },
    { value: 'Kuwait', label: 'Кувейт' },
    { value: 'Kyrgyzstan', label: 'Киргизстан' },
    { value: 'Laos', label: 'Лаос' },
    { value: 'Latvia', label: 'Латвія' },
    { value: 'Lebanon', label: 'Ліван' },
    { value: 'Lesotho', label: 'Лесото' },
    { value: 'Liberia', label: 'Ліберія' },
    { value: 'Libya', label: 'Лівія' },
    { value: 'Liechtenstein', label: 'Ліхтенштейн' },
    { value: 'Lithuania', label: 'Литва' },
    { value: 'Luxembourg', label: 'Люксембург' },
    { value: 'Madagascar', label: 'Мадагаскар' },
    { value: 'Malawi', label: 'Малаві' },
    { value: 'Malaysia', label: 'Малайзія' },
    { value: 'Maldives', label: 'Мальдіви' },
    { value: 'Mali', label: 'Малі' },
    { value: 'Malta', label: 'Мальта' },
    { value: 'Marshall Islands', label: 'Маршаллові Острови' },
    { value: 'Mauritania', label: 'Мавританія' },
    { value: 'Mauritius', label: 'Маврикій' },
    { value: 'Mexico', label: 'Мексика' },
    { value: 'Micronesia', label: 'Мікронезія' },
    { value: 'Moldova', label: 'Молдова' },
    { value: 'Monaco', label: 'Монако' },
    { value: 'Mongolia', label: 'Монголія' },
    { value: 'Montenegro', label: 'Чорногорія' },
    { value: 'Morocco', label: 'Марокко' },
    { value: 'Mozambique', label: 'Мозамбік' },
    { value: 'Myanmar', label: 'Мʼянма' },
    { value: 'Namibia', label: 'Намібія' },
    { value: 'Nauru', label: 'Науру' },
    { value: 'Nepal', label: 'Непал' },
    { value: 'Netherlands', label: 'Нідерланди' },
    { value: 'New Zealand', label: 'Нова Зеландія' },
    { value: 'Nicaragua', label: 'Нікарагуа' },
    { value: 'Niger', label: 'Нігер' },
    { value: 'Nigeria', label: 'Нігерія' },
    { value: 'North Korea', label: 'Північна Корея' },
    { value: 'North Macedonia', label: 'Північна Македонія' },
    { value: 'Norway', label: 'Норвегія' },
    { value: 'Oman', label: 'Оман' },
    { value: 'Pakistan', label: 'Пакистан' },
    { value: 'Palau', label: 'Палау' },
    { value: 'Palestine', label: 'Палестина' },
    { value: 'Panama', label: 'Панама' },
    { value: 'Papua New Guinea', label: 'Папуа — Нова Гвінея' },
    { value: 'Paraguay', label: 'Парагвай' },
    { value: 'Peru', label: 'Перу' },
    { value: 'Philippines', label: 'Філіппіни' },
    { value: 'Poland', label: 'Польща' },
    { value: 'Portugal', label: 'Португалія' },
    { value: 'Qatar', label: 'Катар' },
    { value: 'Romania', label: 'Румунія' },
    { value: 'Russia', label: 'Росія' },
    { value: 'Rwanda', label: 'Руанда' },
    { value: 'Saint Kitts and Nevis', label: 'Сент-Кітс і Невіс' },
    { value: 'Saint Lucia', label: 'Сент-Люсія' },
    { value: 'Saint Vincent and the Grenadines', label: 'Сент-Вінсент і Гренадини' },
    { value: 'Samoa', label: 'Самоа' },
    { value: 'San Marino', label: 'Сан-Марино' },
    { value: 'Sao Tome and Principe', label: 'Сан-Томе і Прінсіпі' },
    { value: 'Saudi Arabia', label: 'Саудівська Аравія' },
    { value: 'Senegal', label: 'Сенегал' },
    { value: 'Serbia', label: 'Сербія' },
    { value: 'Seychelles', label: 'Сейшельські Острови' },
    { value: 'Sierra Leone', label: 'Сьєрра-Леоне' },
    { value: 'Singapore', label: 'Сінгапур' },
    { value: 'Slovakia', label: 'Словаччина' },
    { value: 'Slovenia', label: 'Словенія' },
    { value: 'Solomon Islands', label: 'Соломонові Острови' },
    { value: 'Somalia', label: 'Сомалі' },
    { value: 'South Africa', label: 'Південна Африка' },
    { value: 'South Korea', label: 'Південна Корея' },
    { value: 'South Sudan', label: 'Південний Судан' },
    { value: 'Spain', label: 'Іспанія' },
    { value: 'Sri Lanka', label: 'Шрі-Ланка' },
    { value: 'Sudan', label: 'Судан' },
    { value: 'Suriname', label: 'Суринам' },
    { value: 'Sweden', label: 'Швеція' },
    { value: 'Switzerland', label: 'Швейцарія' },
    { value: 'Syria', label: 'Сирія' },
    { value: 'Tajikistan', label: 'Таджикистан' },
    { value: 'Tanzania', label: 'Танзанія' },
    { value: 'Thailand', label: 'Таїланд' },
    { value: 'Timor-Leste', label: 'Тімор-Лешті' },
    { value: 'Togo', label: 'Того' },
    { value: 'Tonga', label: 'Тонга' },
    { value: 'Trinidad and Tobago', label: 'Тринідад і Тобаго' },
    { value: 'Tunisia', label: 'Туніс' },
    { value: 'Turkey', label: 'Туреччина' },
    { value: 'Turkmenistan', label: 'Туркменістан' },
    { value: 'Tuvalu', label: 'Тувалу' },
    { value: 'Uganda', label: 'Уганда' },
    { value: 'Ukraine', label: 'Україна' },
    { value: 'United Arab Emirates', label: 'Обʼєднані Арабські Емірати' },
    { value: 'United Kingdom', label: 'Обʼєднане Королівство' },
    { value: 'United States', label: 'Сполучені Штати Америки' },
    { value: 'Uruguay', label: 'Уругвай' },
    { value: 'Uzbekistan', label: 'Узбекистан' },
    { value: 'Vanuatu', label: 'Вануату' },
    { value: 'Vatican City', label: 'Ватикан' },
    { value: 'Venezuela', label: 'Венесуела' },
    { value: 'Vietnam', label: 'Вʼєтнам' },
    { value: 'Yemen', label: 'Ємен' },
    { value: 'Zambia', label: 'Замбія' },
    { value: 'Zimbabwe', label: 'Зімбабве' },
  ];

  export default countries;
  