// eslint-disable-next-line
const countries = [
  { value: 'All countries', label: 'Всі країни' },
  { value: 'Afghanistan', label: 'Афганістан', code: 'af' },
  { value: 'Albania', label: 'Албанія', code: 'al' },
  { value: 'Algeria', label: 'Алжир', code: 'dz' },
  { value: 'Andorra', label: 'Андорра', code: 'ad' },
  { value: 'Angola', label: 'Ангола', code: 'ao' },
  { value: 'Antigua and Barbuda', label: 'Антигуа і Барбуда', code: 'ag' },
  { value: 'Argentina', label: 'Аргентина', code: 'ar' },
  { value: 'Armenia', label: 'Вірменія', code: 'am' },
  { value: 'Australia', label: 'Австралія', code: 'au' },
  { value: 'Austria', label: 'Австрія', code: 'at' },
  { value: 'Azerbaijan', label: 'Азербайджан', code: 'az' },
  { value: 'Bahamas', label: 'Багамські Острови', code: 'bs' },
  { value: 'Bahrain', label: 'Бахрейн', code: 'bh' },
  { value: 'Bangladesh', label: 'Бангладеш', code: 'bd' },
  { value: 'Barbados', label: 'Барбадос', code: 'bb' },
  { value: 'Belarus', label: 'Білорусь', code: 'by' },
  { value: 'Belgium', label: 'Бельгія', code: 'be' },
  { value: 'Belize', label: 'Беліз', code: 'bz' },
  { value: 'Benin', label: 'Бенін', code: 'bj' },
  { value: 'Bhutan', label: 'Бутан', code: 'bt' },
  { value: 'Bolivia', label: 'Болівія', code: 'bo' },
  { value: 'Bosnia and Herzegovina', label: 'Боснія і Герцеговина', code: 'ba' },
  { value: 'Botswana', label: 'Ботсвана', code: 'bw' },
  { value: 'Brazil', label: 'Бразилія', code: 'br' },
  { value: 'Brunei', label: 'Бруней', code: 'bn' },
  { value: 'Bulgaria', label: 'Болгарія', code: 'bg' },
  { value: 'Burkina Faso', label: 'Буркіна-Фасо', code: 'bf' },
  { value: 'Burundi', label: 'Бурунді', code: 'bi' },
  { value: 'Cabo Verde', label: 'Кабо-Верде', code: 'cv' },
  { value: 'Cambodia', label: 'Камбоджа', code: 'kh' },
  { value: 'Cameroon', label: 'Камерун', code: 'cm' },
  { value: 'Canada', label: 'Канада', code: 'ca' },
  { value: 'Central African Republic', label: 'Центральноафриканська Республіка', code: 'cf' },
  { value: 'Chad', label: 'Чад', code: 'td' },
  { value: 'Chile', label: 'Чилі', code: 'cl' },
  { value: 'China', label: 'Китай', code: 'cn' },
  { value: 'Colombia', label: 'Колумбія', code: 'co' },
  { value: 'Comoros', label: 'Коморські острови', code: 'km' },
  { value: 'Congo', label: 'Конго', code: 'cg' },
  { value: 'Costa Rica', label: 'Коста-Ріка', code: 'cr' },
  { value: 'Croatia', label: 'Хорватія', code: 'hr' },
  { value: 'Cuba', label: 'Куба', code: 'cu' },
  { value: 'Cyprus', label: 'Кіпр', code: 'cy' },
  { value: 'Czechia', label: 'Чехія', code: 'cz' },
  { value: 'Denmark', label: 'Данія', code: 'dk' },
  { value: 'Djibouti', label: 'Джибуті', code: 'dj' },
  { value: 'Dominica', label: 'Домініка', code: 'dm' },
  { value: 'Dominican Republic', label: 'Домініканська Республіка', code: 'do' },
  { value: 'Ecuador', label: 'Еквадор', code: 'ec' },
  { value: 'Egypt', label: 'Єгипет', code: 'eg' },
  { value: 'El Salvador', label: 'Сальвадор', code: 'sv' },
  { value: 'Equatorial Guinea', label: 'Екваторіальна Гвінея', code: 'gq' },
  { value: 'Eritrea', label: 'Еритрея', code: 'er' },
  { value: 'Estonia', label: 'Естонія', code: 'ee' },
  { value: 'Eswatini', label: 'Есватіні', code: 'sz' },
  { value: 'Ethiopia', label: 'Ефіопія', code: 'et' },
  { value: 'Fiji', label: 'Фіджі', code: 'fj' },
  { value: 'Finland', label: 'Фінляндія', code: 'fi' },
  { value: 'France', label: 'Франція', code: 'fr' },
  { value: 'Gabon', label: 'Габон', code: 'ga' },
  { value: 'Gambia', label: 'Гамбія', code: 'gm' },
  { value: 'Georgia', label: 'Грузія', code: 'ge' },
  { value: 'Germany', label: 'Німеччина', code: 'de' },
  { value: 'Ghana', label: 'Гана', code: 'gh' },
  { value: 'Greece', label: 'Греція', code: 'gr' },
  { value: 'Grenada', label: 'Гренада', code: 'gd' },
  { value: 'Guatemala', label: 'Гватемала', code: 'gt' },
  { value: 'Guinea', label: 'Гвінея', code: 'gn' },
  { value: 'Guinea-Bissau', label: 'Гвінея-Бісау', code: 'gw' },
  { value: 'Guyana', label: 'Гайана', code: 'gy' },
  { value: 'Haiti', label: 'Гаїті', code: 'ht' },
  { value: 'Honduras', label: 'Гондурас', code: 'hn' },
  { value: 'Hungary', label: 'Угорщина', code: 'hu' },
  { value: 'Iceland', label: 'Ісландія', code: 'is' },
  { value: 'India', label: 'Індія', code: 'in' },
  { value: 'Indonesia', label: 'Індонезія', code: 'id' },
  { value: 'Iran', label: 'Іран', code: 'ir' },
  { value: 'Iraq', label: 'Ірак', code: 'iq' },
  { value: 'Ireland', label: 'Ірландія', code: 'ie' },
  { value: 'Israel', label: 'Ізраїль', code: 'il' },
  { value: 'Italy', label: 'Італія', code: 'it' },
  { value: 'Jamaica', label: 'Ямайка', code: 'jm' },
  { value: 'Japan', label: 'Японія', code: 'jp' },
  { value: 'Jordan', label: 'Йорданія', code: 'jo' },
  { value: 'Kazakhstan', label: 'Казахстан', code: 'kz' },
  { value: 'Kenya', label: 'Кенія', code: 'ke' },
  { value: 'Kiribati', label: 'Кірібаті', code: 'ki' },
  { value: 'Korea, Democratic People\'s Republic of', label: 'Північна Корея', code: 'kp' },
  { value: 'Korea, Republic of', label: 'Південна Корея', code: 'kr' },
  { value: 'Kuwait', label: 'Кувейт', code: 'kw' },
  { value: 'Kyrgyzstan', label: 'Киргизстан', code: 'kg' },
  { value: 'Laos', label: 'Лаос', code: 'la' },
  { value: 'Latvia', label: 'Латвія', code: 'lv' },
  { value: 'Lebanon', label: 'Ліван', code: 'lb' },
  { value: 'Lesotho', label: 'Лесото', code: 'ls' },
  { value: 'Liberia', label: 'Ліберія', code: 'lr' },
  { value: 'Libya', label: 'Лівія', code: 'ly' },
  { value: 'Liechtenstein', label: 'Ліхтенштейн', code: 'li' },
  { value: 'Lithuania', label: 'Литва', code: 'lt' },
  { value: 'Luxembourg', label: 'Люксембург', code: 'lu' },
  { value: 'Madagascar', label: 'Мадагаскар', code: 'mg' },
  { value: 'Malawi', label: 'Малаві', code: 'mw' },
  { value: 'Malaysia', label: 'Малайзія', code: 'my' },
  { value: 'Maldives', label: 'Мальдіви', code: 'mv' },
  { value: 'Mali', label: 'Малі', code: 'ml' },
  { value: 'Malta', label: 'Мальта', code: 'mt' },
  { value: 'Marshall Islands', label: 'Маршаллові Острови', code: 'mh' },
  { value: 'Mauritania', label: 'Мавританія', code: 'mr' },
  { value: 'Mauritius', label: 'Маврикій', code: 'mu' },
  { value: 'Mexico', label: 'Мексика', code: 'mx' },
  { value: 'Micronesia (Federated States of)', label: 'Мікронезія', code: 'fm' },
  { value: 'Moldova, Republic of', label: 'Молдова', code: 'md' },
  { value: 'Monaco', label: 'Монако', code: 'mc' },
  { value: 'Mongolia', label: 'Монголія', code: 'mn' },
  { value: 'Montenegro', label: 'Чорногорія', code: 'me' },
  { value: 'Morocco', label: 'Марокко', code: 'ma' },
  { value: 'Mozambique', label: 'Мозамбік', code: 'mz' },
  { value: 'Myanmar', label: 'Мʼянма', code: 'mm' },
  { value: 'Namibia', label: 'Намібія', code: 'na' },
  { value: 'Nauru', label: 'Науру', code: 'nr' },
  { value: 'Nepal', label: 'Непал', code: 'np' },
  { value: 'Netherlands', label: 'Нідерланди', code: 'nl' },
  { value: 'New Zealand', label: 'Нова Зеландія', code: 'nz' },
  { value: 'Nicaragua', label: 'Нікарагуа', code: 'ni' },
  { value: 'Niger', label: 'Нігер', code: 'ne' },
  { value: 'Nigeria', label: 'Нігерія', code: 'ng' },
  { value: 'North Macedonia', label: 'Північна Македонія', code: 'mk' },
  { value: 'Norway', label: 'Норвегія', code: 'no' },
  { value: 'Oman', label: 'Оман', code: 'om' },
  { value: 'Pakistan', label: 'Пакистан', code: 'pk' },
  { value: 'Palau', label: 'Палау', code: 'pw' },
  { value: 'Panama', label: 'Панама', code: 'pa' },
  { value: 'Papua New Guinea', label: 'Папуа-Нова Гвінея', code: 'pg' },
  { value: 'Paraguay', label: 'Параґвай', code: 'py' },
  { value: 'Peru', label: 'Перу', code: 'pe' },
  { value: 'Philippines', label: 'Філіппіни', code: 'ph' },
  { value: 'Poland', label: 'Польща', code: 'pl' },
  { value: 'Portugal', label: 'Португалія', code: 'pt' },
  { value: 'Qatar', label: 'Катар', code: 'qa' },
  { value: 'Romania', label: 'Румунія', code: 'ro' },
  { value: 'Russia', label: 'Росія', code: 'ru' },
  { value: 'Rwanda', label: 'Руанда', code: 'rw' },
  { value: 'Saint Kitts and Nevis', label: 'Сент-Кітс і Невіс', code: 'kn' },
  { value: 'Saint Lucia', label: 'Сент-Люсія', code: 'lc' },
  { value: 'Saint Vincent and the Grenadines', label: 'Сент-Вінсент і Гренадини', code: 'vc' },
  { value: 'Samoa', label: 'Самоа', code: 'ws' },
  { value: 'San Marino', label: 'Сан-Марино', code: 'sm' },
  { value: 'Sao Tome and Principe', label: 'Сан-Томе і Принсіпі', code: 'st' },
  { value: 'Saudi Arabia', label: 'Саудівська Аравія', code: 'sa' },
  { value: 'Senegal', label: 'Сенегал', code: 'sn' },
  { value: 'Serbia', label: 'Сербія', code: 'rs' },
  { value: 'Seychelles', label: 'Сейшельські острови', code: 'sc' },
  { value: 'Sierra Leone', label: 'Сьєрра-Леоне', code: 'sl' },
  { value: 'Singapore', label: 'Сінгапур', code: 'sg' },
  { value: 'Slovakia', label: 'Словаччина', code: 'sk' },
  { value: 'Slovenia', label: 'Словенія', code: 'si' },
  { value: 'Solomon Islands', label: 'Соломонові Острови', code: 'sb' },
  { value: 'Somalia', label: 'Сомалі', code: 'so' },
  { value: 'South Africa', label: 'Південна Африка', code: 'za' },
  { value: 'South Sudan', label: 'Південний Судан', code: 'ss' },
  { value: 'Spain', label: 'Іспанія', code: 'es' },
  { value: 'Sri Lanka', label: 'Шрі-Ланка', code: 'lk' },
  { value: 'Sudan', label: 'Судан', code: 'sd' },
  { value: 'Suriname', label: 'Суринам', code: 'sr' },
  { value: 'Sweden', label: 'Швеція', code: 'se' },
  { value: 'Switzerland', label: 'Швейцарія', code: 'ch' },
  { value: 'Syrian Arab Republic', label: 'Сирія', code: 'sy' },
  { value: 'Tajikistan', label: 'Таджикистан', code: 'tj' },
  { value: 'Tanzania', label: 'Танзанія', code: 'tz' },
  { value: 'Thailand', label: 'Таїланд', code: 'th' },
  { value: 'Timor-Leste', label: 'Тімор-Лешті', code: 'tl' },
  { value: 'Togo', label: 'Того', code: 'tg' },
  { value: 'Tonga', label: 'Тонга', code: 'to' },
  { value: 'Trinidad and Tobago', label: 'Тринідад і Тобаго', code: 'tt' },
  { value: 'Tunisia', label: 'Туніс', code: 'tn' },
  { value: 'Turkey', label: 'Туреччина', code: 'tr' },
  { value: 'Turkmenistan', label: 'Туркменістан', code: 'tm' },
  { value: 'Tuvalu', label: 'Тувалу', code: 'tv' },
  { value: 'Uganda', label: 'Уганда', code: 'ug' },
  { value: 'Ukraine', label: 'Україна', code: 'ua' },
  { value: 'United Arab Emirates', label: 'Обʼєднані Арабські Емірати', code: 'ae' },
  { value: 'United Kingdom', label: 'Велика Британія', code: 'gb' },
  { value: 'United States', label: 'Сполучені Штати', code: 'us' },
  { value: 'Uruguay', label: 'Уругвай', code: 'uy' },
  { value: 'Uzbekistan', label: 'Узбекистан', code: 'uz' },
  { value: 'Vanuatu', label: 'Вануату', code: 'vu' },
  { value: 'Venezuela', label: 'Венесуела', code: 've' },
  { value: 'Viet Nam', label: 'Вʼєтнам', code: 'vn' },
  { value: 'Yemen', label: 'Ємен', code: 'ye' },
  { value: 'Zambia', label: 'Замбія', code: 'zm' },
  { value: 'Zimbabwe', label: 'Зімбабве', code: 'zw' },
];

export default countries;
